name: Nav & Docs Consistency

on:
  pull_request:
    paths:
      - 'docs/**/*.md'
      - 'scripts/generate_nav.py'
      - 'README.md'
  push:
    branches: [ main ]
    paths:
      - 'docs/**/*.md'
      - 'scripts/generate_nav.py'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML
      - name: Generate nav
        run: |
          python scripts/generate_nav.py
      - name: Fail if README not updated
        run: |
          if [[ -n $(git status --porcelain README.md) ]]; then
            echo 'README.md not up to date. Run scripts/generate_nav.py locally and commit.'
            git diff README.md || true
            exit 1
          fi
      - name: Basic link check (relative docs)
        run: |
          python scripts/check_links.py
